# Generated by Django 3.1 on 2020-09-02 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, choices=[('준비위', '준비위'), ('발표자', '발표자')], max_length=15, null=True)),
                ('email', models.CharField(max_length=30, verbose_name='이메일')),
                ('image_url', models.TextField(null=True, verbose_name='사진')),
                ('name', models.CharField(max_length=15, verbose_name='이름')),
                ('introduction', models.TextField(null=True, verbose_name='소개글')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField(verbose_name='로고')),
                ('introduction', models.TextField(null=True, verbose_name='소개글')),
                ('homepage_link', models.CharField(max_length=50, verbose_name='홈페이지')),
                ('sponsorship_rating', models.CharField(max_length=50, verbose_name='후원등급')),
            ],
        ),
        migrations.CreateModel(
            name='SNS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, choices=[('트위터', '트위터'), ('깃허브', '깃허브'), ('페이스북', '페이스북'), ('인스타', '인스타'), ('링크드인', '링크드인'), ('블로그', '블로그')], max_length=15, null=True)),
                ('link', models.TextField(verbose_name='sns링크')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sns', to='sheets.member')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5, verbose_name='연도')),
                ('track_num', models.CharField(max_length=2, verbose_name='트랙번호')),
                ('order', models.CharField(max_length=2, verbose_name='발표순번')),
                ('title', models.TextField(verbose_name='발표제목')),
                ('source_link', models.TextField(verbose_name='자료링크')),
                ('presentation_time', models.CharField(max_length=10, verbose_name='발표시간')),
                ('difficulty', models.CharField(max_length=15, verbose_name='발표 난이도')),
                ('presenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='sheets.member')),
            ],
        ),
    ]
