# Generated by Django 3.1 on 2020-09-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='difficulty',
            field=models.CharField(max_length=15, null=True, verbose_name='발표 난이도'),
        ),
        migrations.AlterField(
            model_name='content',
            name='presentation_time',
            field=models.CharField(max_length=10, null=True, verbose_name='발표시간'),
        ),
    ]
