# Generated by Django 3.1 on 2020-09-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_auto_20200902_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='기업이름'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='homepage_link',
            field=models.TextField(verbose_name='홈페이지'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='image_url',
            field=models.TextField(null=True, verbose_name='로고'),
        ),
    ]
