# Generated by Django 3.1 on 2020-09-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_auto_20200916_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='sponsorship_rating',
            field=models.CharField(blank=True, choices=[('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver')], max_length=50, null=True, verbose_name='후원등급'),
        ),
    ]
