# Generated by Django 3.1 on 2020-09-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0005_auto_20200916_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='introduction',
            field=models.TextField(null=True, verbose_name='내용소개'),
        ),
        migrations.AddField(
            model_name='member',
            name='belongTo',
            field=models.CharField(max_length=30, null=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='content',
            name='order',
            field=models.CharField(max_length=2, null=True, verbose_name='발표순번'),
        ),
        migrations.AlterField(
            model_name='content',
            name='source_link',
            field=models.TextField(null=True, verbose_name='자료링크'),
        ),
        migrations.AlterField(
            model_name='content',
            name='track_num',
            field=models.CharField(max_length=2, null=True, verbose_name='트랙번호'),
        ),
        migrations.AlterField(
            model_name='content',
            name='year',
            field=models.CharField(default='2020', max_length=5, verbose_name='연도'),
        ),
    ]
