# Generated by Django 3.1 on 2020-09-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0006_auto_20200918_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='kind',
            field=models.CharField(blank=True, choices=[('일반 세션', '일반 세션'), ('이그나이트', '이그나이트'), ('스폰서 특별 세션', '스폰서 특별 세션'), ('외부 초청', '외부 초청')], default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='difficulty',
            field=models.CharField(default='', max_length=15, null=True, verbose_name='발표 난이도'),
        ),
        migrations.AlterField(
            model_name='content',
            name='introduction',
            field=models.TextField(default='', null=True, verbose_name='내용소개'),
        ),
        migrations.AlterField(
            model_name='content',
            name='order',
            field=models.CharField(default='', max_length=2, null=True, verbose_name='발표순번'),
        ),
        migrations.AlterField(
            model_name='content',
            name='presentation_time',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='발표시간'),
        ),
        migrations.AlterField(
            model_name='content',
            name='source_link',
            field=models.TextField(default='', null=True, verbose_name='자료링크'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.TextField(default='', verbose_name='발표제목'),
        ),
        migrations.AlterField(
            model_name='content',
            name='track_num',
            field=models.CharField(default='', max_length=2, null=True, verbose_name='트랙번호'),
        ),
        migrations.AlterField(
            model_name='member',
            name='belongTo',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='member',
            name='image_url',
            field=models.TextField(default='', null=True, verbose_name='사진'),
        ),
        migrations.AlterField(
            model_name='member',
            name='introduction',
            field=models.TextField(default='', null=True, verbose_name='소개글'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(default='', max_length=15, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='sns',
            name='kind',
            field=models.CharField(blank=True, choices=[('트위터', '트위터'), ('깃허브', '깃허브'), ('페이스북', '페이스북'), ('인스타', '인스타'), ('링크드인', '링크드인'), ('블로그', '블로그')], default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sns',
            name='link',
            field=models.TextField(default='', verbose_name='sns링크'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='homepage_link',
            field=models.TextField(default='', verbose_name='홈페이지'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='image_url',
            field=models.TextField(default='', null=True, verbose_name='로고'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='introduction',
            field=models.TextField(default='', null=True, verbose_name='소개글'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='기업이름'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsorship_rating',
            field=models.CharField(blank=True, choices=[('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver')], default='', max_length=50, null=True, verbose_name='후원등급'),
        ),
    ]
