# Generated by Django 3.1 on 2020-09-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0008_auto_20200918_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='introduction',
            field=models.TextField(blank=True, default='', null=True, verbose_name='내용소개'),
        ),
        migrations.AlterField(
            model_name='content',
            name='kind',
            field=models.CharField(blank=True, choices=[('일반 세션', '일반 세션'), ('이그나이트', '이그나이트'), ('스폰서 특별 세션', '스폰서 특별 세션'), ('외부 초청', '외부 초청'), ('커뮤니티 콜라보', '커뮤니티 콜라보')], default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.TextField(blank=True, default='', null=True, verbose_name='발표제목'),
        ),
        migrations.AlterField(
            model_name='member',
            name='image_url',
            field=models.TextField(blank=True, default='', null=True, verbose_name='사진'),
        ),
        migrations.AlterField(
            model_name='member',
            name='introduction',
            field=models.TextField(blank=True, default='', null=True, verbose_name='소개글'),
        ),
    ]
